sync openthread to upstream tag v2026.08.0

diff --git a/openthread/script/test b/openthread/script/test
--- a/openthread/script/test
+++ b/openthread/script/test
@@ -68,6 +68,9 @@ readonly VERBOSE
 BORDER_ROUTING="${BORDER_ROUTING:-1}"
 readonly BORDER_ROUTING
 
+DISCOVERY_PROXY="${DISCOVERY_PROXY:-1}"
+readonly DISCOVERY_PROXY
+
 NAT64="${NAT64:-0}"
 readonly NAT64
 
@@ -112,7 +115,7 @@ build_simulation()
         "-DOT_SERVICE=ON"
         "-DOT_SRP_CLIENT=ON"
         "-DOT_SRP_SERVER=ON"
-        "-DOT_SRP_SERVER_FAST_START_MDOE=ON"
+        "-DOT_SRP_SERVER_FAST_START_MODE=ON"
         "-DOT_UPTIME=ON"
         "-DOT_THREAD_VERSION=${version}"
     )
@@ -122,7 +125,6 @@ build_simulation()
     fi
 
     if [[ ${version} != "1.1" ]]; then
-        options+=("-DOT_DUA=ON")
         options+=("-DOT_MLR=ON")
     fi
 
@@ -135,6 +137,7 @@ build_simulation()
         options+=("-DOT_LINK_METRICS_INITIATOR=ON")
         options+=("-DOT_LINK_METRICS_SUBJECT=ON")
         options+=("-DOT_LINK_METRICS_MANAGER=ON")
+        options+=("-DOT_P2P=ON")
         options+=("-DOT_WAKEUP_COORDINATOR=ON")
         options+=("-DOT_WAKEUP_END_DEVICE=ON")
     fi
@@ -160,20 +163,11 @@ build_simulation()
 
     OT_CMAKE_BUILD_DIR="${OT_BUILDDIR}/openthread-simulation-${version}" "${OT_SRCDIR}"/script/cmake-build simulation "${options[@]}"
 
-    if [[ ${VIRTUAL_TIME} == 1 ]] && [[ ${OT_NODE_TYPE} == rcp* ]]; then
-        OT_CMAKE_NINJA_TARGET=ot-rcp OT_CMAKE_BUILD_DIR="${OT_BUILDDIR}/openthread-simulation-${version}" "${OT_SRCDIR}"/script/cmake-build simulation "${options[@]}" "-DOT_SIMULATION_VIRTUAL_TIME_UART=ON"
-    fi
-
     if [[ ${version} != "1.1" && ${INTER_OP_BBR} == 1 ]]; then
 
         options+=("-DOT_BACKBONE_ROUTER=ON")
 
         OT_CMAKE_BUILD_DIR="${OT_BUILDDIR}/openthread-simulation-${version}-bbr" "${OT_SRCDIR}"/script/cmake-build simulation "${options[@]}"
-
-        if [[ ${VIRTUAL_TIME} == 1 ]] && [[ ${OT_NODE_TYPE} == rcp* ]]; then
-            OT_CMAKE_NINJA_TARGET=ot-rcp OT_CMAKE_BUILD_DIR="${OT_BUILDDIR}/openthread-simulation-${version}-bbr" "${OT_SRCDIR}"/script/cmake-build simulation "${options[@]}" "-DOT_SIMULATION_VIRTUAL_TIME_UART=ON"
-        fi
-
     fi
 }
 
@@ -189,11 +183,13 @@ build_posix()
     )
 
     if [[ ${version} != "1.1" ]]; then
-        options+=("-DOT_DUA=ON")
         options+=("-DOT_MLR=ON")
         options+=("-DOT_LINK_METRICS_INITIATOR=ON")
         options+=("-DOT_LINK_METRICS_SUBJECT=ON")
         options+=("-DOT_LINK_METRICS_MANAGER=ON")
+        options+=("-DOT_P2P=ON")
+        options+=("-DOT_WAKEUP_COORDINATOR=ON")
+        options+=("-DOT_WAKEUP_END_DEVICE=ON")
     fi
 
     if [[ ${FULL_LOGS} == 1 ]]; then
@@ -282,7 +278,7 @@ do_cert()
         rcp | rcp-cli | cli)
             export NODE_TYPE=sim
             ;;
-        rcp-ncp | ncp)
+        ncp)
             export NODE_TYPE=ncp-sim
             ;;
     esac
@@ -319,7 +315,7 @@ do_cert_suite()
     sudo modprobe ip6table_filter
 
     mkdir -p ot_testing
-    ./tests/scripts/thread-cert/run_cert_suite.py --run-directory ot_testing --multiply "${MULTIPLY:-1}" "$@"
+    ./tests/scripts/thread-cert/run_cert_suite.py --run-directory ot_testing --multiply "${MULTIPLY:-1}" --timeout "${TEST_TIMEOUT:-0}" "$@"
     exit 0
 }
 
@@ -348,19 +344,17 @@ do_build_otbr_docker()
         "-DOT_ANYCAST_LOCATOR=ON"
         "-DOT_COVERAGE=ON"
         "-DOT_DNS_CLIENT=ON"
-        "-DOT_DUA=ON"
         "-DOT_MLR=ON"
         "-DOT_NETDATA_PUBLISHER=ON"
         "-DOT_SLAAC=ON"
         "-DOT_SRP_CLIENT=ON"
         "-DOT_FULL_LOGS=ON"
         "-DOT_UPTIME=ON"
-        "-DOTBR_DNS_UPSTREAM_QUERY=ON"
-        "-DOTBR_DUA_ROUTING=ON"
         "-DOTBR_DHCP6_PD=ON"
     )
     local args=(
         "BORDER_ROUTING=${BORDER_ROUTING}"
+        "DISCOVERY_PROXY=${DISCOVERY_PROXY}"
         "INFRA_IF_NAME=eth0"
         "BACKBONE_ROUTER=1"
         "REFERENCE_DEVICE=1"
@@ -397,7 +391,7 @@ do_build_otbr_docker()
 
     (
         if [[ -z ${LOCAL_OTBR_DIR} ]]; then
-            ./script/git-tool clone https://github.com/openthread/ot-br-posix.git --depth 1 "${otbrdir}"
+            ./script/git-tool clone https://github.com/openthread/ot-br-posix.git --depth 1 --recurse-submodules --shallow-submodules "${otbrdir}"
         else
             rsync -r \
                 --exclude=third_party/openthread/repo \
@@ -479,10 +473,14 @@ do_expect()
             test_patterns=(-name 'posix-*.exp' -o -name 'cli-*.exp')
             if [[ ${THREAD_VERSION} != "1.1" ]]; then
                 test_patterns+=(-o -name 'v1_2-*.exp')
+                test_patterns+=(-o -name 'v1_5-*.exp')
             fi
         fi
     else
         test_patterns=(-name 'cli-*.exp' -o -name 'simulation-*.exp' -o -name 'cli_non_rcp-*.exp')
+        if [[ ${THREAD_VERSION} != "1.1" ]]; then
+            test_patterns+=(-o -name 'v1_5-*.exp')
+        fi
     fi
 
     if [[ $# != 0 ]]; then
@@ -504,7 +502,6 @@ print_usage()
 ENVIRONMENTS:
     OT_NODE_TYPE    'cli' for CLI simulation, 'ncp' for NCP simulation.
                     'rcp' or 'rcp-cli' for CLI on POSIX platform.
-                    'rcp-ncp' for NCP on POSIX platform.
                     The default is 'cli'.
     OT_NATIVE_IP    1 to enable platform UDP and netif on POSIX platform. The default is 0.
     OT_BUILDDIR     The output directory for cmake build. By default the directory is './build'. For example,
@@ -558,7 +555,7 @@ EXAMPLES:
     $0 clean build expect
     "
 
-    exit "$1"
+    exit "${1:-0}"
 }
 
 do_prepare_coredump_upload()
@@ -752,8 +749,9 @@ main()
                 do_combine_coverage
                 ;;
             *)
-                echo
-                echo -e "${OT_COLOR_FAIL}Warning:${OT_COLOR_NONE} Ignoring: '$1'"
+                echo >&2
+                echo -e "${OT_COLOR_FAIL}Error:${OT_COLOR_NONE} Unrecognized command: '$1'" >&2
+                print_usage 1 >&2
                 ;;
         esac
         shift
